language: php
php:
  - "5.4"
  - "5.3"
before_script:
  - pear config-set auto_discover 1
  - pear install pear.phix-project.org/Autoloader
  - pear install pear.phing.info/phing
  - phpenv rehash
  - phing build-vendor
